imports:
    - { resource: 'services/repositories.yaml' }

parameters:

services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    App\:
        resource: '../src/*'
        exclude: '../src/{Entity,Migrations,Tests,Kernel.php}'

    ##############
    ## UI layer ##
    ##############
    App\UI\Rest\Action\:
        resource: '../src/UI/Rest/Action/*'
        tags:
            - { name: controller.service_arguments }
